### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: com/intellij/database/dialects/mysqlbase/model/MysqlBaseSchema

### ISSUE THREAD

**Issue by rsantos-dh** [Atwix/phpstorm-plugin-feedback#120]
**Describe the bug** (*)

This error happens when I open a magento 2 project after update PhpStorm to 2025.3.

**StackTrace from IDE**

```
java.lang.NoClassDefFoundError: com/intellij/database/dialects/mysqlbase/model/MysqlBaseSchema
	at com.atwix.magento.feature.database.util.MagentoDatabaseUtil.hasDatabaseConnection(MagentoDatabaseUtil.kt:56)
	at com.atwix.magento.feature.database.service.MyIsamEngineUsageService$execute$1$1.run$lambda$0(MyIsamEngineUsageService.kt:33)
	at com.intellij.openapi.application.impl.AppImplKt$rethrowCheckedExceptions$2.invoke(appImpl.kt:126)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runReadAction(NestedLocksThreadingSupport.kt:856)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:1069)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at com.atwix.magento.feature.database.service.MyIsamEngineUsageService$execute$1$1.run(MyIsamEngineUsageService.kt:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:268)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:260)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:259)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:717)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:792)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:748)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:716)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:240)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:268)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:546)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:501)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:173)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:167)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$20(ProgressRunner.java:497)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.intellij.database.dialects.mysqlbase.model.MysqlBaseSchema PluginClassLoader(plugin=PluginMainDescriptor(name=Magento and Adobe Commerce PhpStorm by Atwix, id=com.atwix.magento, version=2025.2.2, isBundled=false, path=D:\jetbrains\configs\PhpStorm2025.2\config\plugins\magento-support-by-atwix), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.graphql.yaml, package=com.intellij.graphql.yaml) <- PluginMainDescriptor(name=GraphQL, id=com.intellij.lang.jsgraphql, version=253.28294.218, package=com.intellij.lang.jsgraphql, isBundled=false, path=D:\jetbrains\configs\PhpStorm2025.2\config\plugins\graphql), ContentModuleDescriptor(id=intellij.graphql.langInjection, package=com.intellij.graphql.langInjection) <- PluginMainDescriptor(name=GraphQL, id=com.intellij.lang.jsgraphql, version=253.28294.218, package=com.intellij.lang.jsgraphql, isBundled=false, path=D:\jetbrains\configs\PhpStorm2025.2\config\plugins\graphql), ContentModuleDescriptor(id=intellij.graphql.javascript, package=com.intellij.graphql.javascript) <- Pl
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2025/12/11
 - Plugin version: 2025.2.2/L
 - PhpStorm version: 2025.3 (PS-253.28294.345)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hi @rsantos-dh ,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project.

Our team is now reviewing the problem, and we'll work on resolving it as quickly as possible. We will keep you updated on our progress, and if we have any questions or need more information from you, we'll reach out.

Once again, thank you for your report, and we'll do our best to address this issue promptly.

Best regards,

**Comment by bohdan-harniuk** [comment]
Hi @rsantos-dh ,

We’ve identified and fixed the bug - the fix will be included in the next release. We’ll keep you updated here once the new version is available.

Thanks again for helping us improve the plugin!
Best regards,

**Comment by bohdan-harniuk** [comment]
Hi @rsantos-dh,

The new plugin version **2025.2.3** is now available. You can see the full changelog [here](https://plugins.jetbrains.com/plugin/20554-magento-and-adobe-commerce-phpstorm-by-atwix/docs/changelog.html).

Please update to this version to receive the fix for this issue.

Thank you.
Best regards,
